require 'java'

require 'jruby-rack'

require 'trinidad/version'
require 'trinidad/core_ext'
require 'trinidad/extensions'
require 'trinidad/configuration'
require 'trinidad/command_line_parser'
require 'trinidad/jars'
require 'trinidad/logging'
require 'trinidad/server'
require 'trinidad/lifecycle/lifecycle_listener_host'
require 'trinidad/lifecycle/lifecycle_listener_base'
require 'trinidad/lifecycle/lifecycle_listener_default'
require 'trinidad/lifecycle/lifecycle_listener_war'
require 'trinidad/web_app'
require 'trinidad/rails_web_app'
require 'trinidad/rackup_web_app'
require 'trinidad/war_web_app'
