require 'java'

require 'jruby-rack'

require 'trinidad/version'
require 'trinidad/extensions'
require 'trinidad/configuration'
require 'trinidad/command_line_parser'
require 'trinidad/jars'
require 'trinidad/logging'
require 'trinidad/server'
require 'trinidad/lifecycle/base'
require 'trinidad/lifecycle/host'
require 'trinidad/lifecycle/web_app/shared'
require 'trinidad/lifecycle/web_app/default'
require 'trinidad/lifecycle/web_app/war'
require 'trinidad/web_app'
